[main]
shell=/usr/bin/fish
font=JetBrainsMono Nerd Font Mono:size=12
pad=2x2
term=foot

[cursor]
style=beam
blink=yes

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh

[colors-dark]
# Gruvbox Material Dark Hard
background=1D2021
foreground=D4BE98

# Normal colors
regular0=1D2021 # bg0
regular1=EA6962 # red
regular2=A9B665 # green
regular3=D8A657 # yellow
regular4=7DAEA3 # blue
regular5=D3869B # purple
regular6=89B482 # aqua
regular7=D4BE98 # fg0

# Bright colors
bright0=504945 # bg3
bright1=EA6962 # red
bright2=A9B665 # green
bright3=D8A657 # yellow
bright4=7DAEA3 # blue
bright5=D3869B # purple
bright6=89B482 # aqua
bright7=DDC7A1 # fg1

# Selection highlighting
selection-background=504945
selection-foreground=D4BE98
